### ISSUE TITLE
[Redmine 3.1] Can't locate method `taggings_count`

### ISSUE THREAD

**Issue by stephenyeargin** [marius-balteanu/redmine_tags#13]
- ran all migrations
- ran the migration specific to `act_as_taggable`

```
[ 2015-11-05 16:22:36.5242 12506/7fc7c0499700 Pool2/Implementation.cpp:1156 ]: [App 6892 stderr] ActionView::Template::Error (undefined method `taggings_count' for #<ActsAsTaggableOn::Tag id: 1, name: "UX">):
[ 2015-11-05 16:22:36.5242 12506/7fc7c0499700 Pool2/Implementation.cpp:1156 ]: [App 6892 stderr]     2:   <%= stylesheet_link_tag 'jquery.tagit.css', plugin: 'redmine_tags' %>
[ 2015-11-05 16:22:36.5242 12506/7fc7c0499700 Pool2/Implementation.cpp:1156 ]: [App 6892 stderr]     3:   <%= stylesheet_link_tag 'redmine_tags', plugin: 'redmine_tags' %>
[ 2015-11-05 16:22:36.5242 12506/7fc7c0499700 Pool2/Implementation.cpp:1156 ]: [App 6892 stderr]     4:   <h3><%= l :tags %></h3>
[ 2015-11-05 16:22:36.5242 12506/7fc7c0499700 Pool2/Implementation.cpp:1156 ]: [App 6892 stderr]     5:   <%= render_sidebar_tags %>
[ 2015-11-05 16:22:36.5242 12506/7fc7c0499700 Pool2/Implementation.cpp:1156 ]: [App 6892 stderr]     6: <% end %>
[ 2015-11-05 16:22:36.5242 12506/7fc7c0499700 Pool2/Implementation.cpp:1156 ]: [App 6892 stderr]   lib/redmine/hook.rb:119:in `block (2 levels) in render_on'
[ 2015-11-05 16:22:36.5243 12506/7fc7c0499700 Pool2/Implementation.cpp:1156 ]: [App 6892 stderr]   lib/redmine/hook.rb:117:in `map'
[ 2015-11-05 16:22:36.5243 12506/7fc7c0499700 Pool2/Implementation.cpp:1156 ]: [App 6892 stderr]   lib/redmine/hook.rb:117:in `block in render_on'
[ 2015-11-05 16:22:36.5243 12506/7fc7c0499700 Pool2/Implementation.cpp:1156 ]: [App 6892 stderr]   lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
[ 2015-11-05 16:22:36.5243 12506/7fc7c0499700 Pool2/Implementation.cpp:1156 ]: [App 6892 stderr]   lib/redmine/hook.rb:61:in `each'
[ 2015-11-05 16:22:36.5243 12506/7fc7c0499700 Pool2/Implementation.cpp:1156 ]: [App 6892 stderr]   lib/redmine/hook.rb:61:in `block in call_hook'
[ 2015-11-05 16:22:36.5243 12506/7fc7c0499700 Pool2/Implementation.cpp:1156 ]: [App 6892 stderr]   lib/redmine/hook.rb:58:in `tap'
[ 2015-11-05 16:22:36.5243 12506/7fc7c0499700 Pool2/Implementation.cpp:1156 ]: [App 6892 stderr]   lib/redmine/hook.rb:58:in `call_hook'
[ 2015-11-05 16:22:36.5243 12506/7fc7c0499700 Pool2/Implementation.cpp:1156 ]: [App 6892 stderr]   lib/redmine/hook.rb:167:in `call_hook'
[ 2015-11-05 16:22:36.5243 12506/7fc7c0499700 Pool2/Implementation.cpp:1156 ]: [App 6892 stderr]   app/views/issues/_sidebar.html.erb:18:in `_app_views_issues__sidebar_html_erb__3140368778940950685_70257930679460'
```

**Comment by marius-balteanu** [comment]
I've merged #12. Can I close this issue?

**Comment by stephenyeargin** [comment]
@marius-balteanu I am still encountering this one, unfortunately.

**Comment by marius-balteanu** [comment]
Ok, we'll try to take a look.

**Comment by marius-balteanu** [comment]
@stephenyeargin, one more question:

Did you follow the below steps?
1. run rake acts_as_taggable_on_engine:install:migrations
2. remove first generated migration from <redmine_root>/db/migrate
3. run rake db:migrate
4. restart redmine.

**Comment by stephenyeargin** [comment]
That fixed it. Specifically the conflicting file that needed to be deleted was:

`db/migrate/20151105054660_add_missing_unique_indices.acts_as_taggable_on_engine.rb`
